### ISSUE TITLE
unexpected results on running ```elton interactions``` twice on local dataset 

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/elton#31]
Currently, when running:

```elton interactions``` twice on a local dataset without pre-existing elton cache (e.g., in datasets/ folder), the following is observed on running the command the second time.

```
$ elton interactions
argumentTypeId	sourceOccurrenceId	sourceCatalogNumber	sourceCollectionCode	sourceCollectionId	sourceInstitutionCode	sourceTaxonId	sourceTaxonName	sourceTaxonRank	sourceTaxonPathIds	sourceTaxonPath	sourceTaxonPathNames	sourceBodyPartId	sourceBodyPartName	sourceLifeStageId	sourceLifeStageName	sourceSexId	sourceSexName	interactionTypeId	interactionTypeName	targetOccurrenceId	targetCatalogNumber	targetCollectionCode	targetCollectionId	targetInstitutionCode	targetTaxonId	targetTaxonName	targetTaxonRank	targetTaxonPathIds	targetTaxonPath	targetTaxonPathNames	targetBodyPartId	targetBodyPartName	targetLifeStageId	targetLifeStageName	targetSexId	targetSexName	basisOfRecordIdbasisOfRecordName	http://rs.tdwg.org/dwc/terms/eventDate	decimalLatitudedecimalLongitude	localityId	localityName	referenceDoi	referenceUrl	referenceCitation	namespace	citation	archiveURI	lastSeenAt	contentHash	eltonVersion
listing interactions [local]... failed.
java.lang.RuntimeException: listing interactions failed.
	at org.globalbioticinteractions.elton.cmd.CmdUtil.handleNamespaces(CmdUtil.java:87)
	at org.globalbioticinteractions.elton.cmd.CmdInteractions.run(CmdInteractions.java:195)
	at org.globalbioticinteractions.elton.cmd.CmdInteractions.run(CmdInteractions.java:180)
	at org.globalbioticinteractions.elton.cmd.CmdLine.run(CmdLine.java:18)
	at org.globalbioticinteractions.elton.cmd.CmdLine.run(CmdLine.java:27)
	at org.globalbioticinteractions.elton.Elton.main(Elton.java:20)
Caused by: org.globalbioticinteractions.dataset.DatasetFinderException: failed to import datasets [local], please check the logs.
	at org.globalbioticinteractions.elton.cmd.CmdUtil.handleNamespaces(CmdUtil.java:83)
	... 5 more
```

expected was that the ```elton interactions``` command produced the same results no matter how often it is executed. Probably introduced by recently introduce feature #29 .

**Comment by jhpoelen** [comment]
Elton v0.9.5, the unexpected results are no longer observed:

```
$ elton interactions | wc -l
listing interactions [local]... done.
12
$ elton interactions | wc -l
listing interactions [local]... done.
12
```
