### ISSUE TITLE
transitive dependency commons-lang3 causes class cast exception

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/elton#49]
See https://github.com/globalbioticinteractions/virus-host-db/runs/4206440928?check_suite_focus=true .

review [local]... |/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Ljava.lang.String; ([Ljava.lang.Object; and [Ljava.lang.String; are in module java.base of loader 'bootstrap')
	at org.eol.globi.service.TaxonUtil.generateTaxonName(TaxonUtil.java:593)
	at org.eol.globi.service.TaxonUtil.generateTargetTaxon(TaxonUtil.java:709)
	at org.eol.globi.service.TaxonUtil.enrichIfNeeded(TaxonUtil.java:754)
	at org.eol.globi.service.TaxonUtil.enrichTaxonNames(TaxonUtil.java:727)
	at org.eol.globi.process.TaxonNameEnricher.on(TaxonNameEnricher.java:34)
	at org.eol.globi.process.InteractionListenerImpl.on(InteractionListenerImpl.java:71)
	at org.eol.globi.data.TableInteractionListenerProxy.on(TableInteractionListenerProxy.java:40)
	at

**Comment by jhpoelen** [comment]
Note the issue does not appear to happen on OpenJDK 8 

However, it does happen with:

```
Miller 5.6.2
s3cmd version 2.2.0
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
elton not found... installing from [https://github.com/globalbioticinteractions/elton/releases/download/0.12.1/elton.jar]
elton version 0.12.1
```

**Comment by jhpoelen** [comment]
reproduced in https://github.com/globalbioticinteractions/elton/actions/runs/1467669277

see attached screenshot 

![Screenshot from 2021-11-16 08-00-40](https://user-images.githubusercontent.com/1084872/142020618-d84e313d-6f2d-405f-841d-654e595d0bf4.png)

**Comment by jhpoelen** [comment]
after upgrading to elton 0.12.2, the issue is no longer observed. 

See https://github.com/globalbioticinteractions/virus-host-db/runs/4229535419?check_suite_focus=true and below

```
   _____ _       ____ _____   _____            _                
  / ____| |     |  _ \_   _| |  __ \          (_)               
 | |  __| | ___ | |_) || |   | |__) |_____   ___  _____      __ 
 | | |_ | |/ _ \|  _ < | |   |  _  // _ \ \ / / |/ _ \ \ /\ / / 
 | |__| | | (_) | |_) || |_  | | \ \  __/\ V /| |  __/\ V  V /  
  \_____|_|\___/|____/_____| |_|  \_\___| \_/ |_|\___| \_/\_/   
 | |           |  ____| | |                                     
 | |__  _   _  | |__  | | |_ ___  _ __                          
 | '_ \| | | | |  __| | | __/ _ \| '_ \                         
 | |_) | |_| | | |____| | || (_) | | | |                        
 |_.__/ \__, | |______|_|\__\___/|_| |_|                        
         __/ |                                                  
        |___/                                                   
Miller 5.6.2
s3cmd version 2.2.0
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
elton not found... installing from [https://github.com/globalbioticinteractions/elton/releases/download/0.12.2/elton.jar]
elton version 0.12.2

Review of [local] started at [2021-11-16T19:27:47+00:00].
updating [local]... -\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-done.
-\creating review [local]... |/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\done.
listing interactions [local]... -\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|done.
listing taxa [local]... -\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|done.

gzip: stdout: Broken pipe

gzip: stdout: Broken pipe
cat: write error: Broken pipe
listing nanopubs [local]... -\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|/-\|-\|done.

gzip: stdout: Broken pipe
cat: write error: Broken pipe

Review of [globalbioticinteractions/virus-host-db] included:
  - 17757 interaction(s)
  - 2 note(s)
  - 17757 info(s)
```
