### ISSUE TITLE
indexing of globalbioticinteractions/saproxylic fails with java.lang.NoClassDefFoundError: Could not initialize class org.apache.jena.rdf. model.ModelFactory

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/elton#51]
when running ```elton names globalbioticinteractions/saproxylic``` - 

listing taxa [globalbioticinteractions/saproxylic]... java.lang.NoClassDefFoundError: Could not initialize class org.apache.jena.rdf.
model.ModelFactory
        at org.eol.globi.data.DatasetImporterForSaproxylic.importStudy(DatasetImporterForSaproxylic.java:61)
        at org.eol.globi.util.DatasetImportUtil.importDataset(DatasetImportUtil.java:65)
        at org.globalbioticinteractions.elton.cmd.CmdUtil.handleSingleNamespace(CmdUtil.java:99)
        at org.globalbioticinteractions.elton.cmd.CmdUtil.lambda$handleNamespaces$1(CmdUtil.java:74)
        at org.globalbioticinteractions.elton.cmd.CmdUtil.handleNamespaces(CmdUtil.java:45)
        at org.globalbioticinteractions.elton.cmd.CmdUtil.handleNamespaces(CmdUtil.java:68)
        at org.globalbioticinteractions.elton.cmd.CmdNames.run(CmdNames.java:37)
        at org.globalbioticinteractions.elton.cmd.CmdNames.run(CmdNames.java:26)
        at org.globalbioticinteractions.elton.cmd.CmdLine.run(CmdLine.java:15)
        at org.globalbioticinteractions.elton.cmd.CmdLine.run(CmdLine.java:24)
        at org.globalbioticinteractions.elton.Elton.main(Elton.java:15)

**Comment by jhpoelen** [comment]
reproduced using a latest dev version of elton -


```
$ elton update globalbioticinteractions/saproxylic
updating [globalbioticinteractions/saproxylic]... java.lang.ExceptionInInitializerError
	at org.eol.globi.data.DatasetImporterForSaproxylic.importStudy(DatasetImporterForSaproxylic.java:61)
	at org.eol.globi.util.DatasetImportUtil.importDataset(DatasetImportUtil.java:65)
	at org.eol.globi.util.DatasetImportUtil.importDataset(DatasetImportUtil.java:39)
	at org.globalbioticinteractions.elton.cmd.CmdUpdate.lambda$run$0(CmdUpdate.java:69)
	at org.globalbioticinteractions.elton.cmd.CmdUtil.handleNamespaces(CmdUtil.java:45)
	at org.globalbioticinteractions.elton.cmd.CmdUpdate.run(CmdUpdate.java:82)
	at org.globalbioticinteractions.elton.cmd.CmdLine.run(CmdLine.java:15)
	at org.globalbioticinteractions.elton.cmd.CmdLine.run(CmdLine.java:24)
	at org.globalbioticinteractions.elton.Elton.main(Elton.java:15)
Caused by: java.lang.NullPointerException
	at org.apache.jena.tdb.sys.EnvTDB.processGlobalSystemProperties(EnvTDB.java:33)
	at org.apache.jena.tdb.TDB.init(TDB.java:254)
	at org.apache.jena.tdb.sys.InitTDB.start(InitTDB.java:29)
	at org.apache.jena.sys.JenaSystem.lambda$init$2(JenaSystem.java:117)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.apache.jena.sys.JenaSystem.forEach(JenaSystem.java:192)
	at org.apache.jena.sys.JenaSystem.forEach(JenaSystem.java:169)
	at org.apache.jena.sys.JenaSystem.init(JenaSystem.java:115)
	at org.apache.jena.rdf.model.ModelFactory.<clinit>(ModelFactory.java:49)
	... 9 more
```

**Comment by jhpoelen** [comment]
after replacing maven-assembly-plugin with maven-shade-plugin, following example of https://github.com/apache/jena/blob/main/jena-fuseki2/jena-fuseki-server/pom.xml as referenced in https://lists.apache.org/thread/b1wl22wxmzgwk9t2tfoq9jh1d7dhctv6 , the issue appears to have been resolved:

```
$ elton update globalbioticinteractions/saproxylic
updating [globalbioticinteractions/saproxylic]... done.
```

and 

```
elton names globalbioticinteractions/saproxylic\
| head -n2
```

produces:

```
taxonId	taxonName	taxonRank	taxonPathIds	taxonPath	taxonPathNames	namespace	citation	archiveURI	lastSeenAt	contentHash	eltonVersion
	Fagus sylvatica					globalbioticinteractions/saproxylic	Stokland, J.; Dahlberg, A.; Meyke, E.; Schigel, D.; Siitonen, J. (2006) The Nordic saproxylic database - a comprehensive overview of the biological diversity in dead wood. 1st European Congress of Conservation Biology - "Diversity for Europe". August 2006, Hungary. Book of Abstracts. Society of Conservation Biology (USA) & Blackwell Publishing (UK) p. 159 .	https://github.com/globalbioticinteractions/saproxylic/archive/19d5c932d77059f5ef3d6134e1539f0bbab460e7.zip	2022-03-25T15:46:48.039Z	8abe998264d163be9300893acfd59be4e28f5ec092ea45f7b89f74b8179d8e47	dev
```
